server:
  port: 8080
  servlet:
    context-path: /spring-jsp

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.100.70.7:1521:XE
    username: student##
    password: student##
    hikari:
      auto-commit: false
      maximum-pool-size: 5

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
