DROP TABLE MEMBER;
DROP TABLE FREE_BOARD;

CREATE TABLE MEMBER
(
    MEMBER_ID   VARCHAR2(20),
    MEMBER_PW   VARCHAR2(20),
    MEMBER_NAME VARCHAR2(30),
    POINT       NUMBER,
    PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE FREE_BOARD
(
    ID         NUMBER,
    CONTENT    VARCHAR2(256),
    WRITER_ID  VARCHAR2(20),
    WRITE_DATE DATE,
    PRIMARY KEY (ID)
);

INSERT INTO MEMBER(MEMBER_ID, MEMBER_PW, MEMBER_NAME, POINT) VALUES ('test', 'test', '테스터', 0);